// your-project/store/index.js

export const state = () => ({
    loremipsum: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ac lectus urna. Aliquam lobortis vulputate risus, quis tempor arcu pharetra vel. Sed semper vel magna vel pulvinar. Duis et lacus augue. Duis eget diam urna. Pellentesque convallis nisl vel justo auctor commodo. Maecenas id luctus ante, et aliquam mauris. Donec auctor turpis sed odio facilisis sollicitudin. Morbi cursus mattis lorem quis dapibus. Proin tellus orci, pretium a lorem at, porta porta neque. Donec mi justo, scelerisque eget semper quis, aliquam id neque. Phasellus imperdiet id felis in volutpat.",
    zonetime: [
        { offset: '-11:00', label: '(GMT-11:00) Niue', tzCode: 'Pacific/Niue', tzName: 'Niue' },
        { offset: '-11:00', label: '(GMT-11:00) Pago Pago', tzCode: 'Pacific/Pago_Pago', tzName: 'Pago Pago' },
        { offset: '-10:00', label: '(GMT-10:00) Hawaii Time', tzCode: 'Pacific/Honolulu', tzName: 'Hawaii Time' },
        { offset: '-10:00', label: '(GMT-10:00) Rarotonga', tzCode: 'Pacific/Rarotonga', tzName: 'Rarotonga' },
        { offset: '-10:00', label: '(GMT-10:00) Tahiti', tzCode: 'Pacific/Tahiti', tzName: 'Tahiti' },
        { offset: '-09:30', label: '(GMT-09:30) Marquesas', tzCode: 'Pacific/Marquesas', tzName: 'Marquesas' },
        { offset: '-09:00', label: '(GMT-09:00) Alaska Time', tzCode: 'America/Anchorage', tzName: 'Alaska Time' },
        { offset: '-09:00', label: '(GMT-09:00) Gambier', tzCode: 'Pacific/Gambier', tzName: 'Gambier' },
        { offset: '-08:00', label: '(GMT-08:00) Pacific Time', tzCode: 'America/Los_Angeles', tzName: 'Pacific Time' },
        { offset: '-08:00', label: '(GMT-08:00) Pacific Time - Tijuana', tzCode: 'America/Tijuana', tzName: 'Pacific Time - Tijuana' },
        { offset: '-08:00', label: '(GMT-08:00) Pacific Time - Vancouver', tzCode: 'America/Vancouver', tzName: 'Pacific Time - Vancouver' },
        { offset: '-08:00', label: '(GMT-08:00) Pacific Time - Whitehorse', tzCode: 'America/Whitehorse', tzName: 'Pacific Time - Whitehorse' },
        { offset: '-08:00', label: '(GMT-08:00) Pitcairn', tzCode: 'Pacific/Pitcairn', tzName: 'Pitcairn' },
        { offset: '-07:00', label: '(GMT-07:00) Mountain Time', tzCode: 'America/Denver', tzName: 'Mountain Time' },
        { offset: '-07:00', label: '(GMT-07:00) Mountain Time - Arizona', tzCode: 'America/Phoenix', tzName: 'Mountain Time - Arizona' },
        { offset: '-07:00', label: '(GMT-07:00) Mountain Time - Chihuahua, Mazatlan', tzCode: 'America/Mazatlan', tzName: 'Mountain Time - Chihuahua, Mazatlan' },
        { offset: '-07:00', label: '(GMT-07:00) Mountain Time - Dawson Creek', tzCode: 'America/Dawson_Creek', tzName: 'Mountain Time - Dawson Creek' },
        { offset: '-07:00', label: '(GMT-07:00) Mountain Time - Edmonton', tzCode: 'America/Edmonton', tzName: 'Mountain Time - Edmonton' },
        { offset: '-07:00', label: '(GMT-07:00) Mountain Time - Hermosillo', tzCode: 'America/Hermosillo', tzName: 'Mountain Time - Hermosillo' },
        { offset: '-07:00', label: '(GMT-07:00) Mountain Time - Yellowknife', tzCode: 'America/Yellowknife', tzName: 'Mountain Time - Yellowknife' },
        { offset: '-06:00', label: '(GMT-06:00) Belize', tzCode: 'America/Belize', tzName: 'Belize' },
        { offset: '-06:00', label: '(GMT-06:00) Central Time', tzCode: 'America/Chicago', tzName: 'Central Time' },
        { offset: '-06:00', label: '(GMT-06:00) Central Time - Mexico City', tzCode: 'America/Mexico_City', tzName: 'Central Time - Mexico City' },
        { offset: '-06:00', label: '(GMT-06:00) Central Time - Regina', tzCode: 'America/Regina', tzName: 'Central Time - Regina' },
        { offset: '-06:00', label: '(GMT-06:00) Central Time - Tegucigalpa', tzCode: 'America/Tegucigalpa', tzName: 'Central Time - Tegucigalpa' },
        { offset: '-06:00', label: '(GMT-06:00) Central Time - Winnipeg', tzCode: 'America/Winnipeg', tzName: 'Central Time - Winnipeg' },
        { offset: '-06:00', label: '(GMT-06:00) Costa Rica', tzCode: 'America/Costa_Rica', tzName: 'Costa Rica' },
        { offset: '-06:00', label: '(GMT-06:00) El Salvador', tzCode: 'America/El_Salvador', tzName: 'El Salvador' },
        { offset: '-06:00', label: '(GMT-06:00) Galapagos', tzCode: 'Pacific/Galapagos', tzName: 'Galapagos' },
        { offset: '-06:00', label: '(GMT-06:00) Guatemala', tzCode: 'America/Guatemala', tzName: 'Guatemala' },
        { offset: '-06:00', label: '(GMT-06:00) Managua', tzCode: 'America/Managua', tzName: 'Managua' },
        { offset: '-05:00', label: '(GMT-05:00) America Cancun', tzCode: 'America/Cancun', tzName: 'America Cancun' },
        { offset: '-05:00', label: '(GMT-05:00) Bogota', tzCode: 'America/Bogota', tzName: 'Bogota' },
        { offset: '-05:00', label: '(GMT-05:00) Easter Island', tzCode: 'Pacific/Easter', tzName: 'Easter Island' },
        { offset: '-05:00', label: '(GMT-05:00) Eastern Time', tzCode: 'America/New_York', tzName: 'Eastern Time' },
        { offset: '-05:00', label: '(GMT-05:00) Eastern Time - Iqaluit', tzCode: 'America/Iqaluit', tzName: 'Eastern Time - Iqaluit' },
        { offset: '-05:00', label: '(GMT-05:00) Eastern Time - Toronto', tzCode: 'America/Toronto', tzName: 'Eastern Time - Toronto' },
        { offset: '-05:00', label: '(GMT-05:00) Guayaquil', tzCode: 'America/Guayaquil', tzName: 'Guayaquil' },
        { offset: '-05:00', label: '(GMT-05:00) Havana', tzCode: 'America/Havana', tzName: 'Havana' },
        { offset: '-05:00', label: '(GMT-05:00) Jamaica', tzCode: 'America/Jamaica', tzName: 'Jamaica' },
        { offset: '-05:00', label: '(GMT-05:00) Lima', tzCode: 'America/Lima', tzName: 'Lima' },
        { offset: '-05:00', label: '(GMT-05:00) Nassau', tzCode: 'America/Nassau', tzName: 'Nassau' },
        { offset: '-05:00', label: '(GMT-05:00) Panama', tzCode: 'America/Panama', tzName: 'Panama' },
        { offset: '-05:00', label: '(GMT-05:00) Port-au-Prince', tzCode: 'America/Port-au-Prince', tzName: 'Port-au-Prince' },
        { offset: '-05:00', label: '(GMT-05:00) Rio Branco', tzCode: 'America/Rio_Branco', tzName: 'Rio Branco' },
        { offset: '-04:00', label: '(GMT-04:00) Atlantic Time - Halifax', tzCode: 'America/Halifax', tzName: 'Atlantic Time - Halifax' },
        { offset: '-04:00', label: '(GMT-04:00) Barbados', tzCode: 'America/Barbados', tzName: 'Barbados' },
        { offset: '-04:00', label: '(GMT-04:00) Bermuda', tzCode: 'Atlantic/Bermuda', tzName: 'Bermuda' },
        { offset: '-04:00', label: '(GMT-04:00) Boa Vista', tzCode: 'America/Boa_Vista', tzName: 'Boa Vista' },
        { offset: '-04:00', label: '(GMT-04:00) Caracas', tzCode: 'America/Caracas', tzName: 'Caracas' },
        { offset: '-04:00', label: '(GMT-04:00) Curacao', tzCode: 'America/Curacao', tzName: 'Curacao' },
        { offset: '-04:00', label: '(GMT-04:00) Grand Turk', tzCode: 'America/Grand_Turk', tzName: 'Grand Turk' },
        { offset: '-04:00', label: '(GMT-04:00) Guyana', tzCode: 'America/Guyana', tzName: 'Guyana' },
        { offset: '-04:00', label: '(GMT-04:00) La Paz', tzCode: 'America/La_Paz', tzName: 'La Paz' },
        { offset: '-04:00', label: '(GMT-04:00) Manaus', tzCode: 'America/Manaus', tzName: 'Manaus' },
        { offset: '-04:00', label: '(GMT-04:00) Martinique', tzCode: 'America/Martinique', tzName: 'Martinique' },
        { offset: '-04:00', label: '(GMT-04:00) Port of Spain', tzCode: 'America/Port_of_Spain', tzName: 'Port of Spain' },
        { offset: '-04:00', label: '(GMT-04:00) Porto Velho', tzCode: 'America/Porto_Velho', tzName: 'Porto Velho' },
        { offset: '-04:00', label: '(GMT-04:00) Puerto Rico', tzCode: 'America/Puerto_Rico', tzName: 'Puerto Rico' },
        { offset: '-04:00', label: '(GMT-04:00) Santo Domingo', tzCode: 'America/Santo_Domingo', tzName: 'Santo Domingo' },
        { offset: '-04:00', label: '(GMT-04:00) Thule', tzCode: 'America/Thule', tzName: 'Thule' },
        { offset: '-03:30', label: '(GMT-03:30) Newfoundland Time - St. Johns', tzCode: 'America/St_Johns', tzName: 'Newfoundland Time - St. Johns' },
        { offset: '-03:00', label: '(GMT-03:00) Araguaina', tzCode: 'America/Araguaina', tzName: 'Araguaina' },
        { offset: '-03:00', label: '(GMT-03:00) Asuncion', tzCode: 'America/Asuncion', tzName: 'Asuncion' },
        { offset: '-03:00', label: '(GMT-03:00) Belem', tzCode: 'America/Belem', tzName: 'Belem' },
        { offset: '-03:00', label: '(GMT-03:00) Buenos Aires', tzCode: 'America/Argentina/Buenos_Aires', tzName: 'Buenos Aires' },
        { offset: '-03:00', label: '(GMT-03:00) Campo Grande', tzCode: 'America/Campo_Grande', tzName: 'Campo Grande' },
        { offset: '-03:00', label: '(GMT-03:00) Cayenne', tzCode: 'America/Cayenne', tzName: 'Cayenne' },
        { offset: '-03:00', label: '(GMT-03:00) Cuiaba', tzCode: 'America/Cuiaba', tzName: 'Cuiaba' },
        { offset: '-03:00', label: '(GMT-03:00) Fortaleza', tzCode: 'America/Fortaleza', tzName: 'Fortaleza' },
        { offset: '-03:00', label: '(GMT-03:00) Godthab', tzCode: 'America/Godthab', tzName: 'Godthab' },
        { offset: '-03:00', label: '(GMT-03:00) Maceio', tzCode: 'America/Maceio', tzName: 'Maceio' },
        { offset: '-03:00', label: '(GMT-03:00) Miquelon', tzCode: 'America/Miquelon', tzName: 'Miquelon' },
        { offset: '-03:00', label: '(GMT-03:00) Montevideo', tzCode: 'America/Montevideo', tzName: 'Montevideo' },
        { offset: '-03:00', label: '(GMT-03:00) Palmer', tzCode: 'Antarctica/Palmer', tzName: 'Palmer' },
        { offset: '-03:00', label: '(GMT-03:00) Paramaribo', tzCode: 'America/Paramaribo', tzName: 'Paramaribo' },
        { offset: '-03:00', label: '(GMT-03:00) Punta Arenas', tzCode: 'America/Punta_Arenas', tzName: 'Punta Arenas' },
        { offset: '-03:00', label: '(GMT-03:00) Recife', tzCode: 'America/Recife', tzName: 'Recife' },
        { offset: '-03:00', label: '(GMT-03:00) Rothera', tzCode: 'Antarctica/Rothera', tzName: 'Rothera' },
        { offset: '-03:00', label: '(GMT-03:00) Salvador', tzCode: 'America/Bahia', tzName: 'Salvador' },
        { offset: '-03:00', label: '(GMT-03:00) Santiago', tzCode: 'America/Santiago', tzName: 'Santiago' },
        { offset: '-03:00', label: '(GMT-03:00) Stanley', tzCode: 'Atlantic/Stanley', tzName: 'Stanley' },
        { offset: '-02:00', label: '(GMT-02:00) Noronha', tzCode: 'America/Noronha', tzName: 'Noronha' },
        { offset: '-02:00', label: '(GMT-02:00) Sao Paulo', tzCode: 'America/Sao_Paulo', tzName: 'Sao Paulo' },
        { offset: '-02:00', label: '(GMT-02:00) South Georgia', tzCode: 'Atlantic/South_Georgia', tzName: 'South Georgia' },
        { offset: '-01:00', label: '(GMT-01:00) Azores', tzCode: 'Atlantic/Azores', tzName: 'Azores' },
        { offset: '-01:00', label: '(GMT-01:00) Cape Verde', tzCode: 'Atlantic/Cape_Verde', tzName: 'Cape Verde' },
        { offset: '-01:00', label: '(GMT-01:00) Scoresbysund', tzCode: 'America/Scoresbysund', tzName: 'Scoresbysund' },
        { offset: '+00:00', label: '(GMT+00:00) Abidjan', tzCode: 'Africa/Abidjan', tzName: 'Abidjan' },
        { offset: '+00:00', label: '(GMT+00:00) Accra', tzCode: 'Africa/Accra', tzName: 'Accra' },
        { offset: '+00:00', label: '(GMT+00:00) Bissau', tzCode: 'Africa/Bissau', tzName: 'Bissau' },
        { offset: '+00:00', label: '(GMT+00:00) Canary Islands', tzCode: 'Atlantic/Canary', tzName: 'Canary Islands' },
        { offset: '+00:00', label: '(GMT+00:00) Casablanca', tzCode: 'Africa/Casablanca', tzName: 'Casablanca' },
        { offset: '+00:00', label: '(GMT+00:00) Danmarkshavn', tzCode: 'America/Danmarkshavn', tzName: 'Danmarkshavn' },
        { offset: '+00:00', label: '(GMT+00:00) Dublin', tzCode: 'Europe/Dublin', tzName: 'Dublin' },
        { offset: '+00:00', label: '(GMT+00:00) El Aaiun', tzCode: 'Africa/El_Aaiun', tzName: 'El Aaiun' },
        { offset: '+00:00', label: '(GMT+00:00) Faeroe', tzCode: 'Atlantic/Faroe', tzName: 'Faeroe' },
        { offset: '+00:00', label: '(GMT+00:00) GMT', tzCode: 'Etc/GMT', tzName: 'GMT' },
        { offset: '+00:00', label: '(GMT+00:00) Lisbon', tzCode: 'Europe/Lisbon', tzName: 'Lisbon' },
        { offset: '+00:00', label: '(GMT+00:00) London', tzCode: 'Europe/London', tzName: 'London' },
        { offset: '+00:00', label: '(GMT+00:00) Monrovia', tzCode: 'Africa/Monrovia', tzName: 'Monrovia' },
        { offset: '+00:00', label: '(GMT+00:00) Reykjavik', tzCode: 'Atlantic/Reykjavik', tzName: 'Reykjavik' },
        { offset: '+01:00', label: '(GMT+01:00) Algiers', tzCode: 'Africa/Algiers', tzName: 'Algiers' },
        { offset: '+01:00', label: '(GMT+01:00) Amsterdam', tzCode: 'Europe/Amsterdam', tzName: 'Amsterdam' },
        { offset: '+01:00', label: '(GMT+01:00) Andorra', tzCode: 'Europe/Andorra', tzName: 'Andorra' },
        { offset: '+01:00', label: '(GMT+01:00) Berlin', tzCode: 'Europe/Berlin', tzName: 'Berlin' },
        { offset: '+01:00', label: '(GMT+01:00) Brussels', tzCode: 'Europe/Brussels', tzName: 'Brussels' },
        { offset: '+01:00', label: '(GMT+01:00) Budapest', tzCode: 'Europe/Budapest', tzName: 'Budapest' },
        { offset: '+01:00', label: '(GMT+01:00) Central European Time - Belgrade', tzCode: 'Europe/Belgrade', tzName: 'Central European Time - Belgrade' },
        { offset: '+01:00', label: '(GMT+01:00) Central European Time - Prague', tzCode: 'Europe/Prague', tzName: 'Central European Time - Prague' },
        { offset: '+01:00', label: '(GMT+01:00) Ceuta', tzCode: 'Africa/Ceuta', tzName: 'Ceuta' },
        { offset: '+01:00', label: '(GMT+01:00) Copenhagen', tzCode: 'Europe/Copenhagen', tzName: 'Copenhagen' },
        { offset: '+01:00', label: '(GMT+01:00) Gibraltar', tzCode: 'Europe/Gibraltar', tzName: 'Gibraltar' },
        { offset: '+01:00', label: '(GMT+01:00) Lagos', tzCode: 'Africa/Lagos', tzName: 'Lagos' },
        { offset: '+01:00', label: '(GMT+01:00) Luxembourg', tzCode: 'Europe/Luxembourg', tzName: 'Luxembourg' },
        { offset: '+01:00', label: '(GMT+01:00) Madrid', tzCode: 'Europe/Madrid', tzName: 'Madrid' },
        { offset: '+01:00', label: '(GMT+01:00) Malta', tzCode: 'Europe/Malta', tzName: 'Malta' },
        { offset: '+01:00', label: '(GMT+01:00) Monaco', tzCode: 'Europe/Monaco', tzName: 'Monaco' },
        { offset: '+01:00', label: '(GMT+01:00) Ndjamena', tzCode: 'Africa/Ndjamena', tzName: 'Ndjamena' },
        { offset: '+01:00', label: '(GMT+01:00) Oslo', tzCode: 'Europe/Oslo', tzName: 'Oslo' },
        { offset: '+01:00', label: '(GMT+01:00) Paris', tzCode: 'Europe/Paris', tzName: 'Paris' },
        { offset: '+01:00', label: '(GMT+01:00) Rome', tzCode: 'Europe/Rome', tzName: 'Rome' },
        { offset: '+01:00', label: '(GMT+01:00) Stockholm', tzCode: 'Europe/Stockholm', tzName: 'Stockholm' },
        { offset: '+01:00', label: '(GMT+01:00) Tirane', tzCode: 'Europe/Tirane', tzName: '' },
        { offset: '+01:00', label: '(GMT+01:00) Tunis', tzCode: 'Africa/Tunis', tzName: '' },
        { offset: '+01:00', label: '(GMT+01:00) Vienna', tzCode: 'Europe/Vienna', tzName: '' },
        { offset: '+01:00', label: '(GMT+01:00) Warsaw', tzCode: 'Europe/Warsaw', tzName: '' },
        { offset: '+01:00', label: '(GMT+01:00) Zurich', tzCode: 'Europe/Zurich', tzName: '' },
        { offset: '+02:00', label: '(GMT+02:00) Amman', tzCode: 'Asia/Amman', tzName: '' },
        { offset: '+02:00', label: '(GMT+02:00) Athens', tzCode: 'Europe/Athens', tzName: '' },
        { offset: '+02:00', label: '(GMT+02:00) Beirut', tzCode: 'Asia/Beirut', tzName: '' },
        { offset: '+02:00', label: '(GMT+02:00) Bucharest', tzCode: 'Europe/Bucharest', tzName: '' },
        { offset: '+02:00', label: '(GMT+02:00) Cairo', tzCode: 'Africa/Cairo', tzName: '' },
        { offset: '+02:00', label: '(GMT+02:00) Chisinau', tzCode: 'Europe/Chisinau', tzName: '' },
        { offset: '+02:00', label: '(GMT+02:00) Damascus', tzCode: 'Asia/Damascus', tzName: '' },
        { offset: '+02:00', label: '(GMT+02:00) Gaza', tzCode: 'Asia/Gaza', tzName: '' },
        { offset: '+02:00', label: '(GMT+02:00) Helsinki', tzCode: 'Europe/Helsinki', tzName: '' },
        { offset: '+02:00', label: '(GMT+02:00) Jerusalem', tzCode: 'Asia/Jerusalem', tzName: '' },
        { offset: '+02:00', label: '(GMT+02:00) Johannesburg', tzCode: 'Africa/Johannesburg', tzName: '' },
        { offset: '+02:00', label: '(GMT+02:00) Khartoum', tzCode: 'Africa/Khartoum', tzName: '' },
        { offset: '+02:00', label: '(GMT+02:00) Kiev', tzCode: 'Europe/Kiev', tzName: '' },
        { offset: '+02:00', label: '(GMT+02:00) Maputo', tzCode: 'Africa/Maputo', tzName: '' },
        { offset: '+02:00', label: '(GMT+02:00) Moscow-01 - Kaliningrad', tzCode: 'Europe/Kaliningrad', tzName: '' },
        { offset: '+02:00', label: '(GMT+02:00) Nicosia', tzCode: 'Asia/Nicosia', tzName: '' },
        { offset: '+02:00', label: '(GMT+02:00) Riga', tzCode: 'Europe/Riga', tzName: '' },
        { offset: '+02:00', label: '(GMT+02:00) Sofia', tzCode: 'Europe/Sofia', tzName: '' },
        { offset: '+02:00', label: '(GMT+02:00) Tallinn', tzCode: 'Europe/Tallinn', tzName: '' },
        { offset: '+02:00', label: '(GMT+02:00) Tripoli', tzCode: 'Africa/Tripoli', tzName: '' },
        { offset: '+02:00', label: '(GMT+02:00) Vilnius', tzCode: 'Europe/Vilnius', tzName: '' },
        { offset: '+02:00', label: '(GMT+02:00) Windhoek', tzCode: 'Africa/Windhoek', tzName: '' },
        { offset: '+03:00', label: '(GMT+03:00) Baghdad', tzCode: 'Asia/Baghdad', tzName: '' },
        { offset: '+03:00', label: '(GMT+03:00) Istanbul', tzCode: 'Europe/Istanbul', tzName: '' },
        { offset: '+03:00', label: '(GMT+03:00) Minsk', tzCode: 'Europe/Minsk', tzName: '' },
        { offset: '+03:00', label: '(GMT+03:00) Moscow+00 - Moscow', tzCode: 'Europe/Moscow', tzName: '' },
        { offset: '+03:00', label: '(GMT+03:00) Nairobi', tzCode: 'Africa/Nairobi', tzName: '' },
        { offset: '+03:00', label: '(GMT+03:00) Qatar', tzCode: 'Asia/Qatar', tzName: '' },
        { offset: '+03:00', label: '(GMT+03:00) Riyadh', tzCode: 'Asia/Riyadh', tzName: '' },
        { offset: '+03:00', label: '(GMT+03:00) Syowa', tzCode: 'Antarctica/Syowa', tzName: '' },
        { offset: '+03:30', label: '(GMT+03:30) Tehran', tzCode: 'Asia/Tehran', tzName: '' },
        { offset: '+04:00', label: '(GMT+04:00) Baku', tzCode: 'Asia/Baku', tzName: '' },
        { offset: '+04:00', label: '(GMT+04:00) Dubai', tzCode: 'Asia/Dubai', tzName: '' },
        { offset: '+04:00', label: '(GMT+04:00) Mahe', tzCode: 'Indian/Mahe', tzName: '' },
        { offset: '+04:00', label: '(GMT+04:00) Mauritius', tzCode: 'Indian/Mauritius', tzName: '' },
        { offset: '+04:00', label: '(GMT+04:00) Moscow+01 - Samara', tzCode: 'Europe/Samara', tzName: '' },
        { offset: '+04:00', label: '(GMT+04:00) Reunion', tzCode: 'Indian/Reunion', tzName: '' },
        { offset: '+04:00', label: '(GMT+04:00) Tbilisi', tzCode: 'Asia/Tbilisi', tzName: '' },
        { offset: '+04:00', label: '(GMT+04:00) Yerevan', tzCode: 'Asia/Yerevan', tzName: '' },
        { offset: '+04:30', label: '(GMT+04:30) Kabul', tzCode: 'Asia/Kabul', tzName: '' },
        { offset: '+05:00', label: '(GMT+05:00) Aqtau', tzCode: 'Asia/Aqtau', tzName: '' },
        { offset: '+05:00', label: '(GMT+05:00) Aqtobe', tzCode: 'Asia/Aqtobe', tzName: '' },
        { offset: '+05:00', label: '(GMT+05:00) Ashgabat', tzCode: 'Asia/Ashgabat', tzName: '' },
        { offset: '+05:00', label: '(GMT+05:00) Dushanbe', tzCode: 'Asia/Dushanbe', tzName: '' },
        { offset: '+05:00', label: '(GMT+05:00) Karachi', tzCode: 'Asia/Karachi', tzName: '' },
        { offset: '+05:00', label: '(GMT+05:00) Kerguelen', tzCode: 'Indian/Kerguelen', tzName: '' },
        { offset: '+05:00', label: '(GMT+05:00) Maldives', tzCode: 'Indian/Maldives', tzName: '' },
        { offset: '+05:00', label: '(GMT+05:00) Mawson', tzCode: 'Antarctica/Mawson', tzName: '' },
        { offset: '+05:00', label: '(GMT+05:00) Moscow+02 - Yekaterinburg', tzCode: 'Asia/Yekaterinburg', tzName: '' },
        { offset: '+05:00', label: '(GMT+05:00) Tashkent', tzCode: 'Asia/Tashkent', tzName: '' },
        { offset: '+05:30', label: '(GMT+05:30) Colombo', tzCode: 'Asia/Colombo', tzName: '' },
        { offset: '+05:30', label: '(GMT+05:30) India Standard Time', tzCode: 'Asia/Kolkata', tzName: '' },
        { offset: '+05:45', label: '(GMT+05:45) Kathmandu', tzCode: 'Asia/Kathmandu', tzName: '' },
        { offset: '+06:00', label: '(GMT+06:00) Almaty', tzCode: 'Asia/Almaty', tzName: '' },
        { offset: '+06:00', label: '(GMT+06:00) Bishkek', tzCode: 'Asia/Bishkek', tzName: '' },
        { offset: '+06:00', label: '(GMT+06:00) Chagos', tzCode: 'Indian/Chagos', tzName: '' },
        { offset: '+06:00', label: '(GMT+06:00) Dhaka', tzCode: 'Asia/Dhaka', tzName: '' },
        { offset: '+06:00', label: '(GMT+06:00) Moscow+03 - Omsk', tzCode: 'Asia/Omsk', tzName: '' },
        { offset: '+06:00', label: '(GMT+06:00) Thimphu', tzCode: 'Asia/Thimphu', tzName: '' },
        { offset: '+06:00', label: '(GMT+06:00) Vostok', tzCode: 'Antarctica/Vostok', tzName: '' },
        { offset: '+06:30', label: '(GMT+06:30) Cocos', tzCode: 'Indian/Cocos', tzName: '' },
        { offset: '+06:30', label: '(GMT+06:30) Rangoon', tzCode: 'Asia/Yangon', tzName: '' },
        { offset: '+07:00', label: '(GMT+07:00) Bangkok', tzCode: 'Asia/Bangkok', tzName: '' },
        { offset: '+07:00', label: '(GMT+07:00) Christmas', tzCode: 'Indian/Christmas', tzName: '' },
        { offset: '+07:00', label: '(GMT+07:00) Davis', tzCode: 'Antarctica/Davis', tzName: '' },
        { offset: '+07:00', label: '(GMT+07:00) Hanoi', tzCode: 'Asia/Saigon', tzName: '' },
        { offset: '+07:00', label: '(GMT+07:00) Hovd', tzCode: 'Asia/Hovd', tzName: '' },
        { offset: '+07:00', label: '(GMT+07:00) Jakarta', tzCode: 'Asia/Jakarta', tzName: '' },
        { offset: '+07:00', label: '(GMT+07:00) Moscow+04 - Krasnoyarsk', tzCode: 'Asia/Krasnoyarsk', tzName: '' },
        { offset: '+08:00', label: '(GMT+08:00) Brunei', tzCode: 'Asia/Brunei', tzName: '' },
        { offset: '+08:00', label: '(GMT+08:00) China Time - Beijing', tzCode: 'Asia/Shanghai', tzName: '' },
        { offset: '+08:00', label: '(GMT+08:00) Choibalsan', tzCode: 'Asia/Choibalsan', tzName: '' },
        { offset: '+08:00', label: '(GMT+08:00) Hong Kong', tzCode: 'Asia/Hong_Kong', tzName: '' },
        { offset: '+08:00', label: '(GMT+08:00) Kuala Lumpur', tzCode: 'Asia/Kuala_Lumpur', tzName: '' },
        { offset: '+08:00', label: '(GMT+08:00) Macau', tzCode: 'Asia/Macau', tzName: '' },
        { offset: '+08:00', label: '(GMT+08:00) Makassar', tzCode: 'Asia/Makassar', tzName: '' },
        { offset: '+08:00', label: '(GMT+08:00) Manila', tzCode: 'Asia/Manila', tzName: '' },
        { offset: '+08:00', label: '(GMT+08:00) Moscow+05 - Irkutsk', tzCode: 'Asia/Irkutsk', tzName: '' },
        { offset: '+08:00', label: '(GMT+08:00) Singapore', tzCode: 'Asia/Singapore', tzName: '' },
        { offset: '+08:00', label: '(GMT+08:00) Taipei', tzCode: 'Asia/Taipei', tzName: '' },
        { offset: '+08:00', label: '(GMT+08:00) Ulaanbaatar', tzCode: 'Asia/Ulaanbaatar', tzName: '' },
        { offset: '+08:00', label: '(GMT+08:00) Western Time - Perth', tzCode: 'Australia/Perth', tzName: '' },
        { offset: '+08:30', label: '(GMT+08:30) Pyongyang', tzCode: 'Asia/Pyongyang', tzName: '' },
        { offset: '+09:00', label: '(GMT+09:00) Dili', tzCode: 'Asia/Dili', tzName: '' },
        { offset: '+09:00', label: '(GMT+09:00) Jayapura', tzCode: 'Asia/Jayapura', tzName: '' },
        { offset: '+09:00', label: '(GMT+09:00) Moscow+06 - Yakutsk', tzCode: 'Asia/Yakutsk', tzName: '' },
        { offset: '+09:00', label: '(GMT+09:00) Palau', tzCode: 'Pacific/Palau', tzName: '' },
        { offset: '+09:00', label: '(GMT+09:00) Seoul', tzCode: 'Asia/Seoul', tzName: '' },
        { offset: '+09:00', label: '(GMT+09:00) Tokyo', tzCode: 'Asia/Tokyo', tzName: '' },
        { offset: '+09:30', label: '(GMT+09:30) Central Time - Darwin', tzCode: 'Australia/Darwin', tzName: '' },
        { offset: '+10:00', label: '(GMT+10:00) Dumont D\'Urville', tzCode: 'Antarctica/DumontDUrville', tzName: '' },
        { offset: '+10:00', label: '(GMT+10:00) Eastern Time - Brisbane', tzCode: 'Australia/Brisbane', tzName: '' },
        { offset: '+10:00', label: '(GMT+10:00) Guam', tzCode: 'Pacific/Guam', tzName: '' },
        { offset: '+10:00', label: '(GMT+10:00) Moscow+07 - Vladivostok', tzCode: 'Asia/Vladivostok', tzName: '' },
        { offset: '+10:00', label: '(GMT+10:00) Port Moresby', tzCode: 'Pacific/Port_Moresby', tzName: '' },
        { offset: '+10:00', label: '(GMT+10:00) Truk', tzCode: 'Pacific/Chuuk', tzName: '' },
        { offset: '+10:30', label: '(GMT+10:30) Central Time - Adelaide', tzCode: 'Australia/Adelaide', tzName: '' },
        { offset: '+11:00', label: '(GMT+11:00) Casey', tzCode: 'Antarctica/Casey', tzName: 'Casey' },
        { offset: '+11:00', label: '(GMT+11:00) Eastern Time - Hobart', tzCode: 'Australia/Hobart', tzName: 'Hobart' },
        { offset: '+11:00', label: '(GMT+11:00) Eastern Time - Melbourne, Sydney', tzCode: 'Australia/Sydney', tzName: 'Melbourne, Sydney' },
        { offset: '+11:00', label: '(GMT+11:00) Efate', tzCode: 'Pacific/Efate', tzName: 'Efate' },
        { offset: '+11:00', label: '(GMT+11:00) Guadalcanal', tzCode: 'Pacific/Guadalcanal', tzName: 'Guadalcanal' },
        { offset: '+11:00', label: '(GMT+11:00) Kosrae', tzCode: 'Pacific/Kosrae', tzName: 'Kosrae' },
        { offset: '+11:00', label: '(GMT+11:00) Moscow+08 - Magadan', tzCode: 'Asia/Magadan', tzName: 'Magadan' },
        { offset: '+11:00', label: '(GMT+11:00) Norfolk', tzCode: 'Pacific/Norfolk', tzName: 'Norfolk' },
        { offset: '+11:00', label: '(GMT+11:00) Noumea', tzCode: 'Pacific/Noumea', tzName: 'Noumea' },
        { offset: '+11:00', label: '(GMT+11:00) Ponape', tzCode: 'Pacific/Pohnpei', tzName: 'Ponape' },
        { offset: '+12:00', label: '(GMT+12:00) Funafuti', tzCode: 'Pacific/Funafuti', tzName: 'Funafuti' },
        { offset: '+12:00', label: '(GMT+12:00) Kwajalein', tzCode: 'Pacific/Kwajalein', tzName: 'Kwajalein' },
        { offset: '+12:00', label: '(GMT+12:00) Majuro', tzCode: 'Pacific/Majuro', tzName: 'Majuro' },
        { offset: '+12:00', label: '(GMT+12:00) Moscow+09 - Petropavlovsk-Kamchatskiy', tzCode: 'Asia/Kamchatka', tzName: 'Petropavlovsk-Kamchatskiy' },
        { offset: '+12:00', label: '(GMT+12:00) Nauru', tzCode: 'Pacific/Nauru', tzName: 'Nauru' },
        { offset: '+12:00', label: '(GMT+12:00) Tarawa', tzCode: 'Pacific/Tarawa', tzName: 'Tarawa' },
        { offset: '+12:00', label: '(GMT+12:00) Wake', tzCode: 'Pacific/Wake', tzName: 'Wake' },
        { offset: '+12:00', label: '(GMT+12:00) Wallis', tzCode: 'Pacific/Wallis', tzName: 'Wallis' },
        { offset: '+13:00', label: '(GMT+13:00) Auckland', tzCode: 'Pacific/Auckland', tzName: 'Auckland' },
        { offset: '+13:00', label: '(GMT+13:00) Enderbury', tzCode: 'Pacific/Enderbury', tzName: 'Enderbury' },
        { offset: '+13:00', label: '(GMT+13:00) Fakaofo', tzCode: 'Pacific/Fakaofo', tzName: 'Fakaofo' },
        { offset: '+13:00', label: '(GMT+13:00) Fiji', tzCode: 'Pacific/Fiji', tzName: 'Fiji' },
        { offset: '+13:00', label: '(GMT+13:00) TOT', tzCode: 'Pacific/Tongatapu', tzName: 'Nuku\'alofa' },
        { offset: '+14:00', label: '(GMT+14:00) WSST', tzCode: 'Pacific/Apia', tzName: 'Apia' },
        { offset: '+14:00', label: '(GMT+14:00) Kiritimati', tzCode: 'Pacific/Kiritimati', tzName: 'Kiritimati' }
      ]
})

export const mutations = {
    SET_VAR_2 (state, value) {
        console.log('SET_VAR_2', value)
        state.var2 = value
    },

    async addArtist(){
        await this.$axios.post(`https://comeback-api.herokuapp.com/artists`, {
            name: 'NCT',
            image: 'https://firebasestorage.googleapis.com/v0/b/comeback-65643.appspot.com/o/images%2Fartists.jpg?alt=media&token=23be3721-5157-45a7-8c0e-e1c03c2e1827',
            type: 'GROUP',
            website: null,
            description:'NCT is a South Korean boy band created by the label SM Entertainment that debuted in 2016. The groups name is short for Neo Culture Technology, a term coined by Lee Soo Man, the founder of SM Entertainment. The concept of the group is to have an unlimited number of members divided into several sub-units around the world. Members are free to stay or leave the group and other members can be added at any time. The long-term goal for the agency is to have active sub-units in several countries such as China, Japan etc...',
            socials:["https://www.facebook.com/2NE1/"],
            platforms:["https://music.youtube.com/channel/UCwPKPUAWE8ah0lkOcvNh8_Q"],
            styles:["KPOP"],
            newGroups:[
            ],
            newMembers:[
                {
                    name: "WayV",
                    image: "https://firebasestorage.googleapis.com/v0/b/comeback-65643.appspot.com/o/images%2F1621573352818?alt=media&token=8de52e50-8996-45e0-9faf-fadb277f1415",
                    type: "GROUP",
                    website: null,
                    description: "WayV (Chinese: 威神V, pinyin: Wēi Shén V) is a Chinese boy band, more precisely it is the fourth sub-unit of the South Korean boy band NCT, so it is considered the Chinese unit of NCT, grouping most of NCTs members of Chinese origin. The group is composed of seven members: Kun, Ten, Winwin, Lucas, Xiaojun, Hendery, and Yangyang.",
                    socials: [
                        "https://www.instagram.com/WayVofficial/"
                    ],
                    platforms: [
                        "https://music.youtube.com/channel/UC5qKojRk3tgoWJZTSVCE9HQ"
                    ],
                    styles: [
                        "KPOP"
                    ]
                },
                {
                    name: "NCT 127",
                    image: "https://firebasestorage.googleapis.com/v0/b/comeback-65643.appspot.com/o/images%2F1621540985155?alt=media&token=3ff50857-9581-4500-b2f9-17bc81634fed",
                    type: "GROUP",
                    website: null,
                    description: "NCT 127 is the second sub-unit revealed and the first sub-unit with an official formation of SM Entertainment's new project, NCT (Neo Culture Technology). The sub-unit consists of Hae Chan, Yuta, Tae Yong, Win Win, Jae Hyun, Mark, Tae Il, Do Young, Johnny and Jung Woo.\n\nThe name of this subunit comes from the fact that Seoul is located on the geographical coordinate of the 127th meridian east (longitude 127°).",
                    socials: [
                        "https://www.facebook.com/NCT127.smtown",
                        "https://twitter.com/NCTsmtown_127",
                        "https://www.instagram.com/nct127/",
                        "https://www.youtube.com/c/nct127",
                        "https://www.vlive.tv/channel/F3C16D",
                        "https://www.snapchat.com/add/nct127_official"
                    ],
                    platforms: [
                        "https://www.deezer.com/fr/artist/50306442",
                        "https://open.spotify.com/artist/7f4ignuCJhLXfZ9giKT7rH",
                        "https://music.youtube.com/channel/UCjqYTQjO-JG-8vLlt6-4iyQ",
                        "https://music.apple.com/fr/artist/nct-127/1235849306"
                    ],
                    styles: [
                        "KPOP"
                    ]
                },
                {
                    name: "NCT DREAM",
                    image: "https://firebasestorage.googleapis.com/v0/b/comeback-65643.appspot.com/o/images%2F1621542931154?alt=media&token=c1143b24-d6de-4308-9e62-6dd4a9729ecc",
                    type: "GROUP",
                    website: null,
                    description: "NCT Dream is the third sub-unit of South Korean boy band NCT, formed by SM Entertainment in 2016 and then as a teen unit of NCT, later evolved away from their youthful image and was renamed in 2020 adults.",
                    socials: [
                        "https://www.facebook.com/NCTDREAM.smtown/",
                        "https://twitter.com/NCTsmtown_DREAM",
                        "https://www.instagram.com/nct_dream/",
                        "https://www.youtube.com/c/nctdream",
                        "https://www.vlive.tv/channel/DB547B"
                    ],
                    platforms: [
                        "https://music.youtube.com/channel/UCuKdaTsJ9Jv94hVV_I9aRxQ",
                        "https://www.deezer.com/fr/artist/11999322",
                        "https://open.spotify.com/artist/1gBUSTR3TyDdTVFIaQnc02",
                        "https://music.apple.com/us/artist/nct-dream/1208839599"
                    ],
                    styles: [
                        "KPOP"
                    ]
                },
            ],
        })
    }
}