const ROLES = {
  ADMIN: 'ADMIN',
  MODERATOR: 'MODERATOR',
  NONE: 'NONE',
};

const REQUESTS = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  DENIED: 'DENIED',
};

const METHODS = {
  POST: 'POST',
  PUT: 'PUT',
  DELETE: 'DELETE',
};

const ARTIST_TYPE = {
  GROUP: 'GROUP',
  SOLO: 'SOLO',
};

export { ROLES, REQUESTS, METHODS, ARTIST_TYPE };
