const ROLES = {
  ADMIN: 'ADMIN',
  MODERATOR: 'MODERATOR',
  NONE: 'NONE',
};

const SUBSCRIPTION = {
  REGULAR: 'REGULAR',
  SUBSCRIBER: 'SUBSCRIBER',
  VIP: 'VIP',
};

const REQUESTS = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  DENIED: 'DENIED',
};

const METHODS = {
  POST: 'POST',
  PUT: 'PUT',
  DELETE: 'DELETE',
};

const ARTIST_TYPE = {
  GROUP: 'GROUP',
  SOLO: 'SOLO',
};

const NOTIFICATION_TYPE = {
  COMMENT: 'COMMENT',
  REQUEST_FEEDBACK: 'REQUEST_FEEDBACK',
  ARTIST: 'ARTIST',
  RELEASE: 'RELEASE',
  GENERAL: 'GENERAL',
};

export { ROLES, SUBSCRIPTION, REQUESTS, METHODS, ARTIST_TYPE, NOTIFICATION_TYPE };
